language: node_js
cache:
  npm: false
node_js:
- lts/*
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: KZ0VSEvR4z9sxJU8RNdWc/1E8yotxrWYOVXkcH7cBtbodW5fRlva5K9DZKJzUf55umzF/zCzudWU740EAkUm4ciFYzEWPbpU4eHLJGInu4fo8zmfyKcJY6AJE4XpjPEs7pJfZyHik2R0ycWggV+Hn0lwXRhobicXRPCsDhLfnFkHIyzCGYQEMzmOzYB0MXvVxlvgxdyZvSbX6tfh6WRBe7KQLEBE6GzBYsXLDyRujyxHtcMOwqT4YVTNI/KEJXxdR7OBxvNKnyLZ68h6uWIPPnV6hfoBKnxKiAbZC+epL0zmpvMMOZoW49+mV1o/OX3sCbmHvGmH6sefV4sslBHEVlh+ARZfFZHfL60XIzbwHzzlfviKwnzrwBjaUTJiTXfl8xm/Z1TwujsIfDeObj1u26vq2aG2UDAqzjSlr8O3NPRV2ApNgK4C4wXrPLtAp8HAkG6U7fG5qdnLFgQCcbj07VMxSZVCcM4ULpeqGnlL1vBS25Qe/Ntpt7DGC/6PA2ucLU9V4FszaNgn2fQ9fyKa6z1v8fOuq2Lpes4lUx1LYR06Vu4yca3yEIEsT7jry3MfKNiuFP/KbgTgV8cU+dLbIrJRlu6D5vslzNSExGAHXCCZv6BfJXXa/nyff6NhczpD2hhNZRdojWX01AGKWNi+5K+mPoU78O58N/gZ+4cpv2Q=
